/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITomiLPInterface extends ethers.utils.Interface {
  functions: {
    "tokenA()": FunctionFragment;
    "tokenB()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;

  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;

  events: {};
}

export class ITomiLP extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITomiLPInterface;

  functions: {
    tokenA(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tokenA()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tokenB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tokenB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  tokenA(overrides?: CallOverrides): Promise<string>;

  "tokenA()"(overrides?: CallOverrides): Promise<string>;

  tokenB(overrides?: CallOverrides): Promise<string>;

  "tokenB()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    tokenA(overrides?: CallOverrides): Promise<string>;

    "tokenA()"(overrides?: CallOverrides): Promise<string>;

    tokenB(overrides?: CallOverrides): Promise<string>;

    "tokenB()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenA(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenA()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenB(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenB()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenA()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
