/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenRegistryInterface extends ethers.utils.Interface {
  functions: {
    "CLOSED()": FunctionFragment;
    "NONE()": FunctionFragment;
    "OPENED()": FunctionFragment;
    "PENDING()": FunctionFragment;
    "REGISTERED()": FunctionFragment;
    "changeGovernor(address)": FunctionFragment;
    "governor()": FunctionFragment;
    "iterateValidTokens(uint256,uint256)": FunctionFragment;
    "publishTime(address)": FunctionFragment;
    "publishToken(address)": FunctionFragment;
    "registryToken(address)": FunctionFragment;
    "tokenCount()": FunctionFragment;
    "tokenList(uint256)": FunctionFragment;
    "tokenStatus(address)": FunctionFragment;
    "updateToken(address,uint256)": FunctionFragment;
    "validTokens()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "CLOSED", values?: undefined): string;
  encodeFunctionData(functionFragment: "NONE", values?: undefined): string;
  encodeFunctionData(functionFragment: "OPENED", values?: undefined): string;
  encodeFunctionData(functionFragment: "PENDING", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REGISTERED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeGovernor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "iterateValidTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "publishTime", values: [string]): string;
  encodeFunctionData(
    functionFragment: "publishToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registryToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tokenStatus", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validTokens",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "CLOSED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "NONE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OPENED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PENDING", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "REGISTERED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "iterateValidTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registryToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validTokens",
    data: BytesLike
  ): Result;

  events: {
    "ChangeGovernor(address,address)": EventFragment;
    "TokenStatusChanged(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangeGovernor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenStatusChanged"): EventFragment;
}

export class TokenRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenRegistryInterface;

  functions: {
    CLOSED(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "CLOSED()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    NONE(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "NONE()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    OPENED(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "OPENED()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    PENDING(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "PENDING()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    REGISTERED(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "REGISTERED()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    changeGovernor(
      _new: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeGovernor(address)"(
      _new: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    governor(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "governor()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    iterateValidTokens(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "iterateValidTokens(uint256,uint256)"(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    publishTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "publishTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    publishToken(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publishToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registryToken(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registryToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tokenCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "tokenCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    tokenList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tokenList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    tokenStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "tokenStatus(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    updateToken(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateToken(address,uint256)"(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    validTokens(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;

    "validTokens()"(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;
  };

  CLOSED(overrides?: CallOverrides): Promise<BigNumber>;

  "CLOSED()"(overrides?: CallOverrides): Promise<BigNumber>;

  NONE(overrides?: CallOverrides): Promise<BigNumber>;

  "NONE()"(overrides?: CallOverrides): Promise<BigNumber>;

  OPENED(overrides?: CallOverrides): Promise<BigNumber>;

  "OPENED()"(overrides?: CallOverrides): Promise<BigNumber>;

  PENDING(overrides?: CallOverrides): Promise<BigNumber>;

  "PENDING()"(overrides?: CallOverrides): Promise<BigNumber>;

  REGISTERED(overrides?: CallOverrides): Promise<BigNumber>;

  "REGISTERED()"(overrides?: CallOverrides): Promise<BigNumber>;

  changeGovernor(
    _new: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeGovernor(address)"(
    _new: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  governor(overrides?: CallOverrides): Promise<string>;

  "governor()"(overrides?: CallOverrides): Promise<string>;

  iterateValidTokens(
    _start: BigNumberish,
    _end: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "iterateValidTokens(uint256,uint256)"(
    _start: BigNumberish,
    _end: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  publishTime(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "publishTime(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  publishToken(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publishToken(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registryToken(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registryToken(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

  "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  tokenList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokenList(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  tokenStatus(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "tokenStatus(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateToken(
    _token: string,
    _status: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateToken(address,uint256)"(
    _token: string,
    _status: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  validTokens(overrides?: CallOverrides): Promise<string[]>;

  "validTokens()"(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    CLOSED(overrides?: CallOverrides): Promise<BigNumber>;

    "CLOSED()"(overrides?: CallOverrides): Promise<BigNumber>;

    NONE(overrides?: CallOverrides): Promise<BigNumber>;

    "NONE()"(overrides?: CallOverrides): Promise<BigNumber>;

    OPENED(overrides?: CallOverrides): Promise<BigNumber>;

    "OPENED()"(overrides?: CallOverrides): Promise<BigNumber>;

    PENDING(overrides?: CallOverrides): Promise<BigNumber>;

    "PENDING()"(overrides?: CallOverrides): Promise<BigNumber>;

    REGISTERED(overrides?: CallOverrides): Promise<BigNumber>;

    "REGISTERED()"(overrides?: CallOverrides): Promise<BigNumber>;

    changeGovernor(_new: string, overrides?: CallOverrides): Promise<void>;

    "changeGovernor(address)"(
      _new: string,
      overrides?: CallOverrides
    ): Promise<void>;

    governor(overrides?: CallOverrides): Promise<string>;

    "governor()"(overrides?: CallOverrides): Promise<string>;

    iterateValidTokens(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "iterateValidTokens(uint256,uint256)"(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    publishTime(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "publishTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishToken(_token: string, overrides?: CallOverrides): Promise<boolean>;

    "publishToken(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registryToken(_token: string, overrides?: CallOverrides): Promise<boolean>;

    "registryToken(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokenList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    tokenStatus(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "tokenStatus(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateToken(
      _token: string,
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "updateToken(address,uint256)"(
      _token: string,
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validTokens(overrides?: CallOverrides): Promise<string[]>;

    "validTokens()"(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {
    ChangeGovernor(_old: string | null, _new: string | null): EventFilter;

    TokenStatusChanged(
      _token: string | null,
      _status: null,
      _block: null
    ): EventFilter;
  };

  estimateGas: {
    CLOSED(overrides?: CallOverrides): Promise<BigNumber>;

    "CLOSED()"(overrides?: CallOverrides): Promise<BigNumber>;

    NONE(overrides?: CallOverrides): Promise<BigNumber>;

    "NONE()"(overrides?: CallOverrides): Promise<BigNumber>;

    OPENED(overrides?: CallOverrides): Promise<BigNumber>;

    "OPENED()"(overrides?: CallOverrides): Promise<BigNumber>;

    PENDING(overrides?: CallOverrides): Promise<BigNumber>;

    "PENDING()"(overrides?: CallOverrides): Promise<BigNumber>;

    REGISTERED(overrides?: CallOverrides): Promise<BigNumber>;

    "REGISTERED()"(overrides?: CallOverrides): Promise<BigNumber>;

    changeGovernor(_new: string, overrides?: Overrides): Promise<BigNumber>;

    "changeGovernor(address)"(
      _new: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    "governor()"(overrides?: CallOverrides): Promise<BigNumber>;

    iterateValidTokens(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "iterateValidTokens(uint256,uint256)"(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishTime(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "publishTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishToken(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "publishToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registryToken(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "registryToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenStatus(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "tokenStatus(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateToken(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateToken(address,uint256)"(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    validTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "validTokens()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CLOSED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "CLOSED()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    NONE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "NONE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    OPENED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "OPENED()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PENDING(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PENDING()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REGISTERED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REGISTERED()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeGovernor(
      _new: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeGovernor(address)"(
      _new: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    iterateValidTokens(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "iterateValidTokens(uint256,uint256)"(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publishTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "publishTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publishToken(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publishToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registryToken(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registryToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tokenCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenStatus(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateToken(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateToken(address,uint256)"(
      _token: string,
      _status: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    validTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "validTokens()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
