/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TomiBallotInterface extends ethers.utils.Interface {
  functions: {
    "TOMI()": FunctionFragment;
    "content()": FunctionFragment;
    "createTime()": FunctionFragment;
    "delegate(address)": FunctionFragment;
    "end()": FunctionFragment;
    "endTime()": FunctionFragment;
    "ended()": FunctionFragment;
    "executionTime()": FunctionFragment;
    "governor()": FunctionFragment;
    "proposals(uint256)": FunctionFragment;
    "proposer()": FunctionFragment;
    "result()": FunctionFragment;
    "subject()": FunctionFragment;
    "total()": FunctionFragment;
    "value()": FunctionFragment;
    "voteByGovernor(address,uint256)": FunctionFragment;
    "voters(address)": FunctionFragment;
    "weight(address)": FunctionFragment;
    "winningProposal()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "TOMI", values?: undefined): string;
  encodeFunctionData(functionFragment: "content", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "delegate", values: [string]): string;
  encodeFunctionData(functionFragment: "end", values?: undefined): string;
  encodeFunctionData(functionFragment: "endTime", values?: undefined): string;
  encodeFunctionData(functionFragment: "ended", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executionTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "proposer", values?: undefined): string;
  encodeFunctionData(functionFragment: "result", values?: undefined): string;
  encodeFunctionData(functionFragment: "subject", values?: undefined): string;
  encodeFunctionData(functionFragment: "total", values?: undefined): string;
  encodeFunctionData(functionFragment: "value", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteByGovernor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "voters", values: [string]): string;
  encodeFunctionData(functionFragment: "weight", values: [string]): string;
  encodeFunctionData(
    functionFragment: "winningProposal",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "TOMI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "content", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "end", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ended", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "result", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "total", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "value", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteByGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weight", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningProposal",
    data: BytesLike
  ): Result;

  events: {};
}

export class TomiBallot extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TomiBallotInterface;

  functions: {
    TOMI(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "TOMI()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    content(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "content()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    createTime(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "createTime()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    delegate(to: string, overrides?: Overrides): Promise<ContractTransaction>;

    "delegate(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    end(overrides?: Overrides): Promise<ContractTransaction>;

    "end()"(overrides?: Overrides): Promise<ContractTransaction>;

    endTime(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "endTime()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    ended(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "ended()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    executionTime(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "executionTime()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    governor(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "governor()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    proposer(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "proposer()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    result(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "result()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    subject(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "subject()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    total(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "total()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    value(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "value()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    voteByGovernor(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "voteByGovernor(address,uint256)"(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      weight: BigNumber;
      voted: boolean;
      delegate: string;
      vote: BigNumber;
      0: BigNumber;
      1: boolean;
      2: string;
      3: BigNumber;
    }>;

    "voters(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      weight: BigNumber;
      voted: boolean;
      delegate: string;
      vote: BigNumber;
      0: BigNumber;
      1: boolean;
      2: string;
      3: BigNumber;
    }>;

    weight(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "weight(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    winningProposal(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "winningProposal()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  TOMI(overrides?: CallOverrides): Promise<string>;

  "TOMI()"(overrides?: CallOverrides): Promise<string>;

  content(overrides?: CallOverrides): Promise<string>;

  "content()"(overrides?: CallOverrides): Promise<string>;

  createTime(overrides?: CallOverrides): Promise<BigNumber>;

  "createTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  delegate(to: string, overrides?: Overrides): Promise<ContractTransaction>;

  "delegate(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  end(overrides?: Overrides): Promise<ContractTransaction>;

  "end()"(overrides?: Overrides): Promise<ContractTransaction>;

  endTime(overrides?: CallOverrides): Promise<BigNumber>;

  "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  ended(overrides?: CallOverrides): Promise<boolean>;

  "ended()"(overrides?: CallOverrides): Promise<boolean>;

  executionTime(overrides?: CallOverrides): Promise<BigNumber>;

  "executionTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  governor(overrides?: CallOverrides): Promise<string>;

  "governor()"(overrides?: CallOverrides): Promise<string>;

  proposals(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "proposals(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proposer(overrides?: CallOverrides): Promise<string>;

  "proposer()"(overrides?: CallOverrides): Promise<string>;

  result(overrides?: CallOverrides): Promise<boolean>;

  "result()"(overrides?: CallOverrides): Promise<boolean>;

  subject(overrides?: CallOverrides): Promise<string>;

  "subject()"(overrides?: CallOverrides): Promise<string>;

  total(overrides?: CallOverrides): Promise<BigNumber>;

  "total()"(overrides?: CallOverrides): Promise<BigNumber>;

  value(overrides?: CallOverrides): Promise<BigNumber>;

  "value()"(overrides?: CallOverrides): Promise<BigNumber>;

  voteByGovernor(
    user: string,
    proposal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "voteByGovernor(address,uint256)"(
    user: string,
    proposal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  voters(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    weight: BigNumber;
    voted: boolean;
    delegate: string;
    vote: BigNumber;
    0: BigNumber;
    1: boolean;
    2: string;
    3: BigNumber;
  }>;

  "voters(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    weight: BigNumber;
    voted: boolean;
    delegate: string;
    vote: BigNumber;
    0: BigNumber;
    1: boolean;
    2: string;
    3: BigNumber;
  }>;

  weight(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "weight(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  winningProposal(overrides?: CallOverrides): Promise<BigNumber>;

  "winningProposal()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    TOMI(overrides?: CallOverrides): Promise<string>;

    "TOMI()"(overrides?: CallOverrides): Promise<string>;

    content(overrides?: CallOverrides): Promise<string>;

    "content()"(overrides?: CallOverrides): Promise<string>;

    createTime(overrides?: CallOverrides): Promise<BigNumber>;

    "createTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(to: string, overrides?: CallOverrides): Promise<void>;

    "delegate(address)"(to: string, overrides?: CallOverrides): Promise<void>;

    end(overrides?: CallOverrides): Promise<boolean>;

    "end()"(overrides?: CallOverrides): Promise<boolean>;

    endTime(overrides?: CallOverrides): Promise<BigNumber>;

    "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    ended(overrides?: CallOverrides): Promise<boolean>;

    "ended()"(overrides?: CallOverrides): Promise<boolean>;

    executionTime(overrides?: CallOverrides): Promise<BigNumber>;

    "executionTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<string>;

    "governor()"(overrides?: CallOverrides): Promise<string>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposer(overrides?: CallOverrides): Promise<string>;

    "proposer()"(overrides?: CallOverrides): Promise<string>;

    result(overrides?: CallOverrides): Promise<boolean>;

    "result()"(overrides?: CallOverrides): Promise<boolean>;

    subject(overrides?: CallOverrides): Promise<string>;

    "subject()"(overrides?: CallOverrides): Promise<string>;

    total(overrides?: CallOverrides): Promise<BigNumber>;

    "total()"(overrides?: CallOverrides): Promise<BigNumber>;

    value(overrides?: CallOverrides): Promise<BigNumber>;

    "value()"(overrides?: CallOverrides): Promise<BigNumber>;

    voteByGovernor(
      user: string,
      proposal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "voteByGovernor(address,uint256)"(
      user: string,
      proposal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      weight: BigNumber;
      voted: boolean;
      delegate: string;
      vote: BigNumber;
      0: BigNumber;
      1: boolean;
      2: string;
      3: BigNumber;
    }>;

    "voters(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      weight: BigNumber;
      voted: boolean;
      delegate: string;
      vote: BigNumber;
      0: BigNumber;
      1: boolean;
      2: string;
      3: BigNumber;
    }>;

    weight(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "weight(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;

    "winningProposal()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    TOMI(overrides?: CallOverrides): Promise<BigNumber>;

    "TOMI()"(overrides?: CallOverrides): Promise<BigNumber>;

    content(overrides?: CallOverrides): Promise<BigNumber>;

    "content()"(overrides?: CallOverrides): Promise<BigNumber>;

    createTime(overrides?: CallOverrides): Promise<BigNumber>;

    "createTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(to: string, overrides?: Overrides): Promise<BigNumber>;

    "delegate(address)"(to: string, overrides?: Overrides): Promise<BigNumber>;

    end(overrides?: Overrides): Promise<BigNumber>;

    "end()"(overrides?: Overrides): Promise<BigNumber>;

    endTime(overrides?: CallOverrides): Promise<BigNumber>;

    "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    ended(overrides?: CallOverrides): Promise<BigNumber>;

    "ended()"(overrides?: CallOverrides): Promise<BigNumber>;

    executionTime(overrides?: CallOverrides): Promise<BigNumber>;

    "executionTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    "governor()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposer(overrides?: CallOverrides): Promise<BigNumber>;

    "proposer()"(overrides?: CallOverrides): Promise<BigNumber>;

    result(overrides?: CallOverrides): Promise<BigNumber>;

    "result()"(overrides?: CallOverrides): Promise<BigNumber>;

    subject(overrides?: CallOverrides): Promise<BigNumber>;

    "subject()"(overrides?: CallOverrides): Promise<BigNumber>;

    total(overrides?: CallOverrides): Promise<BigNumber>;

    "total()"(overrides?: CallOverrides): Promise<BigNumber>;

    value(overrides?: CallOverrides): Promise<BigNumber>;

    "value()"(overrides?: CallOverrides): Promise<BigNumber>;

    voteByGovernor(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "voteByGovernor(address,uint256)"(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    voters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "voters(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    weight(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "weight(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;

    "winningProposal()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    TOMI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "TOMI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    content(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "content()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "createTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegate(to: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "delegate(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    end(overrides?: Overrides): Promise<PopulatedTransaction>;

    "end()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    endTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "endTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ended(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ended()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executionTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "executionTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proposer()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    result(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "result()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    subject(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "subject()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    total(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "total()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    value(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "value()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    voteByGovernor(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "voteByGovernor(address,uint256)"(
      user: string,
      proposal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "voters(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    weight(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "weight(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winningProposal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "winningProposal()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
