/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITomiFactory } from "../ITomiFactory";

export class ITomiFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITomiFactory {
    return new Contract(address, _abi, signerOrProvider) as ITomiFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
